#!/usr/bin/env bash

if [ -f './.git/todo-filter' ]
then
    function filter
    {
	./.git/todo-filter
    }
else
    function filter
    {
	cat
    }
fi

if [ "$1" = "--progress" ] || [ "$1" = "-p" ]
then
    function progress
    {
	echo -en '\e[2m'
	echo -n "$*"
	echo -e '\e[m'
    }
else
    function progress
    {
	:
    }
fi

colour=1
for todo in $(echo XXX TODO FIXME)
do
    colour=$(( $colour + 1 ))
    if [ $colour = 4 ]
    then
	colour=1
    fi
    find "./" | grep -v '\/\.git\/' | grep -v '\/_\/' |
    grep -v '.\.png$' | grep -v '.\.jpeg$' | grep -v '.\.gif$' |
    grep -v '.\.xcf$' | grep -v '.\.pdf$' | grep -v '.\.ps$' |
    grep -v '.\.div$' | grep -v '.\.info$' | grep -v '.\.gz$' |
    grep -v '~$' | grep -v '.\.info' | filter | 
    while read file
    do
	if [ -f "$file" ]
	then
	    progress "$file"
	    seded=$(sed -e s/'\\'/'\\\\'/g <<<${file} |
		    sed -e s/'\/'/'\\\/'/g |
		    sed -e s/'\^'/'\\\^'/g -e s/'\$'/'\\\$'/g -e s/'\.'/'\\\.'/g -e s/'\['/'\\\]'/g -e s/'\]'/'\\\]'/g)
	    grep -nI --colour=always $todo "$file" |
	    grep -v "$(echo -e '^\e\\[.*m\e\\[K\\.')" |
	    sed -e s/'^'/'\x1b\[35m\x1b\[K'"$seded"'\x1b\[m\x1b\[K\x1b\[36m\x1b\[K:\x1b\[m\x1b\[K'/ |
	    sed -e s/'\x1b\[01;31m'/'\x1b\[01;3'"$colour"'m'/g
	fi
    done
done

find "./" | grep -v '\/\.git\/' | grep -i '\/TODO$' |
while read file
do
    echo -en '\e[01;34m'
    echo -n "$file"
    echo -e '\e[m'
    cat "$file"
done
