#!/usr/bin/env bash

repo=$PWD
while [ ! -d "$repo/.git" ]; do
    if [ "$repo" = '' ]; then
        echo 'reposity is not initialised' 1>&2
        exit 1
    fi
    repo=${repo%/*}
done

echo $repo

