#!/usr/bin/env bash

dia -- "$@"

for file in "$@"; do
    if [[ ! -d "$file" ]]; then
	if [[ -e "$file" ]]; then
	    git add -- "$file"
	fi
	if [[ -L "$file" ]]; then
	    git add -- "$(readlink "$file")"
	fi
    fi
done
