#!/usr/bin/env bash

repo=$PWD
while [ ! -d "$repo/.git" ]; do
    if [ "$repo" = '' ]; then
        echo 'reposity is not initialised' 1>&2
        exit 1
    fi
    repo=${repo%/*}
done

action="$1"

if [ "$action" = "init" ]; then
     mkdir $repo/.git/git-issues &&
       cd $repo/.git/git-issues &&
       git init &&
       git checkout --orphan _issues &&
       echo 'issues by the git extension git-extensions, command git-issues' > README &&
       git add README &&
       git commit -m 'first commit' &&
       echo done
elif [ "$action" = "" ]; then
    if [ ! -d $repo/.git/git-issues/.git ]; then
         echo 'issues is not initialised' 1>&2
	 exit 1
    fi
    cd $repo/.git/git-issues &&
      git-.issues "`git config user.email`" "`git config user.name`" |
        while read line; do
	  "$line"
        done
else
    cd $repo/.git/git-issues &&
      git "$@" &&
      echo done
fi

