#!/usr/bin/env bash

chmod "$@"

dashed=0
skip=0

for arg in "$@"; do
    if [[ $skip = 1 ]]; then
	skip=0
    elif [[ $dashed = 1 ]]; then
	git add "$arg"
    elif [[ "$arg" = "--" ]]; then
	dashed=1
    elif [[ "${arg:0:1}" = "-" ]]; then
	if [[ "$arg" = "--reference" ]]; then
	    skip=1
	fi
    elif [[ -e "$arg" ]]; then
	git add "$arg"
    fi
done

