#!/usr/bin/env bash

repo=$PWD
while [ ! -d "$repo/.git" ]; do
    if [ "$repo" = '' ]; then
        echo 'reposity is not initialised' 1>&2
        exit 1
    fi
    repo=${repo%/*}
done

action="$1"

if [ "$action" = "init" ]; then
     mkdir $repo/.git/git-issues &&
       cd $repo/.git/git-issues &&
       git init &&
       git checkout --orphan .issues &&
       echo 'issues by the git extension git-extensions, command git-issues' > README &&
       git add README &&
       gitcom 'first commit'
fi

