#!/usr/bin/env bash

cp "$@"
if [[ -d "${@:$#}" ]]; then
    i=1
    dir="${@:$#:1}"
    while (( $i < $# )); do
	file="${@:$i:1}"
	file="${file##*/}"
	git add "$dir/$file"
	i=$(( $i + 1 ))
    done
else
    git add "${@:$#:1}"
fi
